select T.niveis, T.filho from (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T left join (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T2 on 1=1;

select T.niveis, T.filho as filho, T2.filho as pai, T.esquerda, T.direita from (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho, group_concat(node.lft) as esquerda, group_concat(node.rgt) as direita from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T left join (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T2 on T.niveis - T2.niveis < 2 where T.niveis - T2.niveis > 0;


select T.niveis, T.filho as filho, T2.filho as pai, T.esquerda, T.direita from (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho, group_concat(parent.lft) as esquerda, group_concat(parent.rgt) as direita from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T left join (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T2 on T.niveis - T2.niveis < 2 where T.niveis - T2.niveis > 0;

select T.niveis, T.filho as filho, T2.filho as pai, T.esquerda, T.direita from (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho, node.lft as esquerda, node.rgt as direita from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T left join (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T2 on T.niveis - T2.niveis < 2 where T.niveis - T2.niveis > 0;

select T.niveis, T.filho as filho, T2.filho as pai, T.esquerda, T.direita from (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho, node.lft as esquerda, node.rgt as direita from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria order by MAX(node.lft)) as T left join (select count(parent.nome_categoria) - 1 as niveis, node.nome_categoria as filho from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt group by node.nome_categoria, node.lft, node.rgt order by MAX(node.lft)) as T2 on T.niveis - T2.niveis < 2 where T.niveis - T2.niveis > 0;


select ST.niveis, ST.filho as filho, ST.esquerda, ST.direita from (select count(T.pai) - 1 as niveis, T.filho as filho, T.esquerda as esquerda, T.direita as direita from (select node.nome_categoria as filho, parent.nome_categoria as pai, node.lft as esquerda, node.rgt as direita from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt) as T group by T.filho, T.esquerda, T.direita) as ST;


select T_filho.niveis, T_filho.filho, T_pai.filho as pai from (select ST.niveis as niveis, ST.filho as filho, ST.esquerda, ST.direita from (select count(T.pai) - 1 as niveis, T.filho as filho, T.esquerda as esquerda, T.direita as direita from (select node.nome_categoria as filho, parent.nome_categoria as pai, node.lft as esquerda, node.rgt as direita from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt) as T group by T.filho, T.esquerda, T.direita) as ST) as T_filho left join (select ST2.niveis as niveis, ST2.filho as filho, ST2.esquerda, ST2.direita from (select count(T.pai) - 1 as niveis, T.filho as filho, T.esquerda as esquerda, T.direita as direita from (select node.nome_categoria as filho, parent.nome_categoria as pai, node.lft as esquerda, node.rgt as direita from secoes as node, secoes as parent where node.lft between parent.lft and parent.rgt) as T group by T.filho, T.esquerda, T.direita) as ST2) as T_pai on T_filho.niveis - T_pai.niveis <2 where T_filho.niveis - T_pai.niveis > 0 and T_filho.esquerda between T_pai.esquerda and T_pai.direita; 
