cp ../../latex/USPSC-3.1/USPSC-TCC-modelo.tex ../../latex/USPSC-3.1/USPSC-TCC-modelo_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AnexosTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AnexosTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap1-IntroducaoTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap1-IntroducaoTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-fichacatalograficaTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-fichacatalograficaTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AbstractTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AbstractTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-SimbolosTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-SimbolosTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-EpigrafeTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-EpigrafeTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ResumoTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ResumoTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-IndicesTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-IndicesTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap3-CitacoesTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap3-CitacoesTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ApendicesTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ApendicesTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-DedicatoriaTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-DedicatoriaTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap4-ReferenciasTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap4-ReferenciasTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AgradecimentosTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AgradecimentosTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-IndicesRemissivos.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-IndicesRemissivos_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ErrataTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ErrataTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap2-DesenvolvimentoTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap2-DesenvolvimentoTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap5-ConclusaoTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap5-ConclusaoTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AbreviaturasSiglasTutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AbreviaturasSiglasTutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo-ICMCp.tex ../../latex/USPSC-3.1/USPSC-modelo-ICMCp_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-pre-textual-EESC.tex ../../latex/USPSC-3.1/USPSC-pre-textual-EESC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-modelo-EESC.tex ../../latex/USPSC-3.1/USPSC-TCC-modelo-EESC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-unidades.tex ../../latex/USPSC-3.1/USPSC-unidades_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-pre-textual-IQSC.tex ../../latex/USPSC-3.1/USPSC-pre-textual-IQSC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo-ICMCe.tex ../../latex/USPSC-3.1/USPSC-modelo-ICMCe_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo-IQSC.tex ../../latex/USPSC-3.1/USPSC-modelo-IQSC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-Anexos.tex ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-Anexos_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-IndicesRemissivos.tex ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-IndicesRemissivos_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-Apendices.tex ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-Apendices_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-pre-textual-IAU.tex ../../latex/USPSC-3.1/USPSC-pre-textual-IAU_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-modelo-IQSC.tex ../../latex/USPSC-3.1/USPSC-TCC-modelo-IQSC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo-IFSCp.tex ../../latex/USPSC-3.1/USPSC-modelo-IFSCp_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-ICMC.tex ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-ICMC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial.tex ../../latex/USPSC-3.1/USPSC-Tutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/modelo_RedarTex.tex ../../latex/USPSC-3.1/modelo_RedarTex_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo-EESC.tex ../../latex/USPSC-3.1/USPSC-modelo-EESC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-IQSC.tex ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-IQSC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-pre-textual-IFSC.tex ../../latex/USPSC-3.1/USPSC-pre-textual-IFSC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-modelo-ICMCe.tex ../../latex/USPSC-3.1/USPSC-TCC-modelo-ICMCe_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap3-Conclusao.tex ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap3-Conclusao_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap1-Introducao.tex ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap1-Introducao_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento.tex ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-modelo-ICMCp.tex ../../latex/USPSC-3.1/USPSC-TCC-modelo-ICMCp_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-Tutorial-num.tex ../../latex/USPSC-3.1/USPSC-Tutorial-num_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-pre-textual-Tutorial.tex ../../latex/USPSC-3.1/USPSC-pre-textual-Tutorial_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-pre-textual-OUTRO.tex ../../latex/USPSC-3.1/USPSC-pre-textual-OUTRO_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-IndicesRemissivos.tex ../../latex/USPSC-3.1/USPSC-IndicesRemissivos_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-EESC.tex ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-EESC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo-IAU.tex ../../latex/USPSC-3.1/USPSC-modelo-IAU_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo.tex ../../latex/USPSC-3.1/USPSC-modelo_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-pre-textual-ICMC.tex ../../latex/USPSC-3.1/USPSC-pre-textual-ICMC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Simbolos.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Simbolos_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-folhadeaprovacao.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-folhadeaprovacao_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Abstract.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Abstract_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-CapaICMC.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-CapaICMC_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Epigrafe.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Epigrafe_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-fichacatalografica.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-fichacatalografica_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Resumo.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Resumo_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Agradecimentos.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Agradecimentos_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Dedicatoria.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Dedicatoria_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Errata.tex ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Errata_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-OUTROS.tex ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-OUTROS_RedarTex.tex
cp ../../latex/USPSC-3.1/USPSC-modelo-IFSCe.tex ../../latex/USPSC-3.1/USPSC-modelo-IFSCe_RedarTex.tex
