sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-SimbolosTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap3-CitacoesTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ApendicesTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AgradecimentosTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-DedicatoriaTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap2-DesenvolvimentoTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ResumoTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-ErrataTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AbreviaturasSiglasTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-IndicesTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-EpigrafeTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap5-ConclusaoTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap1-IntroducaoTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AnexosTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-Cap4-ReferenciasTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-AbstractTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial/USPSC-fichacatalograficaTutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-modelo-EESC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/dissertacao_elaine_2022_10_10_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-pre-textual-OUTRO_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-unidades_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo-IFSCe_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-Anexos_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PosTextual/USPSC-Apendices_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial-num_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo-EESC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-modelo_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-Tutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-modelo-ICMCp_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-pre-textual-IQSC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/Pre_textual_UTFPR_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/.Pre_textual_UTFPR_RedarTex.tex.swp
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-modelo-ICMCe_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo-ICMCp_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo-IAU_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo-IQSC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-EESC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap1-Introducao_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-Textual/USPSC-Cap3-Conclusao_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-pre-textual-EESC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo-IFSCp_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo-ICMCe_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-pre-textual-ICMC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/dissertacao_elaine_2022_09_16_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-OUTROS_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-pre-textual-IAU_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-modelo-IQSC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-modelo_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-pre-textual-IFSC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-pre-textual-Tutorial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/.USPSC-modelo-IAU_RedarTex.tex.swp
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-IQSC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-CapaICMC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Dedicatoria_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Agradecimentos_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Simbolos_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-fichacatalografica_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/.lista-abreviaturas-2_RedarTex.tex.swp
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/lista-abreviaturas_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Epigrafe_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/abstract-especial_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-folhadeaprovacao_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Resumo_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Errata_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/USPSC-Abstract_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TA-PreTextual/lista-abreviaturas-2_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/USPSC-TCC-pre-textual-ICMC_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/USPSC-3.1/versao_final_da_capa_pode_copiar_direto_em_cima_do_USPSC_pre_RedarTex.tex
sed -i "s/@\[orientadorficha\]@/Camargo, Paulo S\\\'ergio e Mammana, Victor Pellegrini/g" ../../latex/lista-abreviaturas-2_RedarTex.tex
