rm -f USPSC-modelo-IAU_RedarTex.aux
rm -f USPSC-pre-textual-IAU.aux
rm -f USPSC-TA-PosTextual/USPSC-Apendices_RedarTex.aux
rm -f USPSC-TA-PosTextual/USPSC-Anexos_RedarTex.aux
rm -f USPSC-TA-PosTextual/USPSC-IndicesRemissivos_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-Errata_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-Abstract_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-Dedicatoria_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-Simbolos_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-Agradecimentos_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-Epigrafe_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas_RedarTex.aux
rm -f USPSC-TA-PreTextual/USPSC-Resumo_RedarTex.aux
rm -f USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento_RedarTex.aux
rm -f USPSC-TA-Textual/USPSC-Cap3-Conclusao_RedarTex.aux
rm -f USPSC-TA-Textual/USPSC-Cap1-Introducao_RedarTex.aux
rm -f USPSC-unidades.aux
rm -f USPSC-modelo-IAU_RedarTex.toc
rm -f USPSC-modelo-IAU_RedarTex.log
rm -f USPSC-TA-PreTextual/USPSC-fichacatalografica.pdf
