sed -i "s/Ä/\\\"A/g" teste_RedarTex.tex
sed -i "s/Ä/\\\"A/g" teste.tex
sed -i "s/Ä/\\\"A/g" USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-IndicesRemissivos.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-EESC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-EESC.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IAU_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IAU.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-ICMCe_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-ICMCe.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-ICMCp_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-ICMCp.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IFSCe_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IFSCe.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IFSCp_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IFSCp.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IQSC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo-IQSC.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-modelo.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-EESC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-EESC.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-IAU_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-IAU.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-ICMC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-ICMC.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-IFSC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-IFSC.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-IQSC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-IQSC.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-OUTRO_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-OUTRO.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-Tutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-pre-textual-Tutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PosTextual/USPSC-Anexos_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PosTextual/USPSC-IndicesRemissivos.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PosTextual/USPSC-Apendices_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PosTextual/USPSC-Apendices.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PosTextual/USPSC-Anexos.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PosTextual/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Resumo.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Errata_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Agradecimentos.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-CapaICMC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-folhadeaprovacao.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Epigrafe_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Dedicatoria_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-fichacatalografica_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-folhadeaprovacao_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Errata.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Agradecimentos_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Simbolos_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Resumo_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Abstract_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-fichacatalografica.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-CapaICMC.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Simbolos.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Dedicatoria.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Abstract.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-PreTextual/USPSC-Epigrafe.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-Textual/USPSC-Cap1-Introducao_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-Textual/USPSC-Cap1-Introducao.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-Textual/USPSC-Cap3-Conclusao.tex
sed -i "s/Ä/\\\"A/g" USPSC-TA-Textual/USPSC-Cap3-Conclusao_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-EESC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-EESC.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-ICMCe_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-ICMCe.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-ICMCp_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-ICMCp.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-IQSC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo-IQSC.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-modelo.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-EESC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-EESC.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-ICMC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-ICMC.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-IQSC_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-IQSC.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-OUTROS_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-TCC-pre-textual-OUTROS.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AbreviaturasSiglasTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap1-IntroducaoTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-ErrataTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-DedicatoriaTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-ResumoTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AbstractTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-IndicesRemissivos.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap5-ConclusaoTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AgradecimentosTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-ErrataTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-IndicesTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AbstractTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AnexosTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap5-ConclusaoTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-fichacatalograficaTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AnexosTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap1-IntroducaoTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-SimbolosTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-SimbolosTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-DedicatoriaTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-EpigrafeTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-ApendicesTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AbreviaturasSiglasTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap2-DesenvolvimentoTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-AgradecimentosTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap4-ReferenciasTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-EpigrafeTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap3-CitacoesTutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-IndicesTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap3-CitacoesTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap4-ReferenciasTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-ApendicesTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-ResumoTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-Cap2-DesenvolvimentoTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-fichacatalograficaTutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial-num_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial-num.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-Tutorial.tex
sed -i "s/Ä/\\\"A/g" USPSC-unidades_RedarTex.tex
sed -i "s/Ä/\\\"A/g" USPSC-unidades.tex
