sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo3/capitulo3_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo3/capitulo3.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/.utfprct-dados_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo4/capitulo4.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo4/capitulo4_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/teste_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/utfprct.tex.espera
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/utfprct.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/.utfprct_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/utfprct_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/utfprct-dados_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/utfprct_RedarTex.tex.espera
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/entradas-glossario_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/anexoa_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/apendicea.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/apendiceb_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/anexoa.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/apendicea_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/apendiceb.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PosTexto/entradas-glossario.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo1/capitulo1.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo1/capitulo1_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/teste.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo2/capitulo2_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo2/capitulo2.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/.dedicatoria_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/entradas-acronimos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/agradecimentos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/entradas-acronimos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/resumo.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/agradecimentos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/resumo_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/lista-abrevituras-pristine.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/.epigrafe_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/errata_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/abstract.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/abstract_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/errata.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/file-acronimos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/dedicatoria.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/epigrafe.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/lista-abrevituras-pristine_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/file-simbolos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/epigrafe_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/dedicatoria_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/file-acronimos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/PreTexto/file-simbolos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/.teste_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo5/capitulo5.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/Capitulo5/capitulo5_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/CapituloExemplo/capituloexemplo.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/CapituloExemplo/capituloexemplo_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./utfpr/utfprct-tex/utfprct-dados.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./lista-abreviaturas-2_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-SimbolosTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AnexosTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap1-IntroducaoTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-fichacatalograficaTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap3-CitacoesTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AbstractTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-SimbolosTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-ApendicesTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-EpigrafeTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-ResumoTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AgradecimentosTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-DedicatoriaTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-IndicesTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap3-CitacoesTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-ApendicesTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap2-DesenvolvimentoTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-ResumoTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-DedicatoriaTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap4-ReferenciasTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-ErrataTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AgradecimentosTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AbreviaturasSiglasTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-IndicesTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-IndicesRemissivos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-ErrataTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-EpigrafeTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap5-ConclusaoTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap2-DesenvolvimentoTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap1-IntroducaoTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap5-ConclusaoTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AnexosTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AbreviaturasSiglasTutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-Cap4-ReferenciasTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-AbstractTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial/USPSC-fichacatalograficaTutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-EESC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/dissertacao_elaine_2022_10_10_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-ICMCp.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-EESC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-EESC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-unidades.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-OUTRO_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-IQSC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-ICMCe.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-unidades_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IQSC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IFSCe_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PosTextual/USPSC-Anexos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PosTextual/USPSC-IndicesRemissivos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PosTextual/USPSC-Anexos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PosTextual/USPSC-Apendices.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PosTextual/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PosTextual/USPSC-Apendices_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-IAU.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial-num_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-EESC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/dissertacao_elaine_2022_09_16.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-IQSC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IFSCp.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-ICMC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-ICMCp_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-IQSC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-EESC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-IQSC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/Pre_textual_UTFPR_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/.Pre_textual_UTFPR_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-ICMCe_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-IFSC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-ICMCp_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IAU_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IQSC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-ICMCe.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-EESC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-Textual/USPSC-Cap1-Introducao_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-Textual/USPSC-Cap3-Conclusao.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-Textual/USPSC-Cap1-Introducao.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-Textual/USPSC-Cap2-Desenvolvimento.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-Textual/USPSC-Cap3-Conclusao_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-EESC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-ICMCp.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-Tutorial-num.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IFSCp_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-Tutorial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-ICMCe_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-ICMC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-OUTRO.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-IndicesRemissivos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/dissertacao_elaine_2022_09_16_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-OUTROS_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-IAU_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-modelo-IQSC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-IFSC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-EESC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-IndicesRemissivos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-Tutorial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/.USPSC-modelo-IAU_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IAU.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-IQSC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/dissertacao_elaine_2022_10_10.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/Pre_textual_UTFPR.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-pre-textual-ICMC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-CapaICMC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Simbolos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-folhadeaprovacao.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Abstract.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Dedicatoria_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/lista-abreviaturas.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-CapaICMC.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Agradecimentos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Epigrafe.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-fichacatalografica.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Simbolos_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-fichacatalografica_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/.lista-abreviaturas-2_RedarTex.tex.swp
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/lista-abreviaturas_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Epigrafe_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Resumo.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/abstract-especial_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-folhadeaprovacao_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/abstract-especial.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Agradecimentos.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-AbreviaturasSiglas.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Resumo_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Errata_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Dedicatoria.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Abstract_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/USPSC-Errata.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/lista-abreviaturas-2_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TA-PreTextual/lista-abreviaturas-2.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-OUTROS.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-modelo-IFSCe.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/USPSC-TCC-pre-textual-ICMC_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./USPSC-3.1/versao_final_da_capa_pode_copiar_direto_em_cima_do_USPSC_pre_RedarTex.tex
sed -i "s/Nome da Unidade USP/@[unidadefaculdade]@/g" ../../latex/./lista-abreviaturas-2.tex
