start transaction;
call insere_a_direita_dos_filhos('metodos_para_historia', 'paragrafo_dif_154', 'Seria exagero dizer que a presente pesquisa seguiu a tradição de Annales quando definiu o camimnho seguido em sua pesquisa histórica.', '', (select id_chave_nested_tipo_secao from nested_tipos_secoes where nome_nested_tipo_secao = 'paragrafo'));
call insere_a_direita_dos_filhos('metodos_para_historia', 'auto_dif_2022-11-12_14:28:59.556', 'O grandes autores da Escola de Annales se debruçaram sobre longos períodos da história, identificando suas estruturas, conjunturas e fatos.', '', (select id_chave_nested_tipo_secao from nested_tipos_secoes where nome_nested_tipo_secao = 'paragrafo'));
call insere_a_direita_dos_filhos('metodos_para_historia', 'auto_dif_2022-11-12_14:31:13.771', 'Em nossa pesquisa concentramo-nos em um período bastante curto e recente, que se inicia na década de 60, quando a pesquisa em sistemas digitais adentraram a academia brasileira, e culmina com os programas de disseminação de cultura digital, já no século XXI.', '', (select id_chave_nested_tipo_secao from nested_tipos_secoes where nome_nested_tipo_secao = 'paragrafo'));
call insere_a_direita_dos_filhos('metodos_para_historia', 'auto_dif_2022-11-12_14:32:43.372', 'Não obstante o reconhecimento dos limites de nossa pesquisa, em comparação com a grandeza dos trabalhos historiográficos da Escola de Annales, pensamos que é possível traçar um paralelo com o que aquele movimento trouxe de positivo para a historiografia.', '', (select id_chave_nested_tipo_secao from nested_tipos_secoes where nome_nested_tipo_secao = 'paragrafo'));
call insere_a_direita_dos_filhos('metodos_para_historia', 'auto_dif_2022-11-12_14:34:03.139', 'No presente trabalho abidicamos de uma visão personalista dos atores que levaram à criação do projeto WASH, tentando compreender as relações de causa e efeito que levaram ao movimento que hoje está em curso.', '', (select id_chave_nested_tipo_secao from nested_tipos_secoes where nome_nested_tipo_secao = 'paragrafo'));
call insere_a_direita_dos_filhos('metodos_para_historia', 'auto_dif_2022-11-12_14:35:40.387', 'Assim, ao conduzir a pesquisa em 3 eixos, nos distanciamos da mera identificação de fatos históricos isolados, buscando aumentar a confiabilidade de nossas afirmações, pela condução de uma análise que "bebe" em métodos complementares.', '', (select id_chave_nested_tipo_secao from nested_tipos_secoes where nome_nested_tipo_secao = 'paragrafo'));
call insere_a_direita_dos_filhos('metodos_para_historia', 'auto_dif_2022-11-12_14:37:30.375', 'Em termos de método historiográfico, o que fizemos se aproxima do que é descrito por  [[PIERANTI (2022)]].', '', (select id_chave_nested_tipo_secao from nested_tipos_secoes where nome_nested_tipo_secao = 'paragrafo'));
commit;
